repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-ast
          - id: check-builtin-literals
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-vcs-permalinks
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: file-contents-sorter
          - id: forbid-new-submodules
          - id: mixed-line-ending
          - id: no-commit-to-branch
          - id: pretty-format-json
          - id: requirements-txt-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace
            language_version: python3

    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            language_version: python3
            additional_dependencies:
                [
                    flake8-2020~=1.6.1,
                    flake8-bugbear~=22.3.23,
                    flake8-builtins~=1.5.3,
                    flake8-comprehensions~=3.8.0,
                    dlint~=0.12.0,
                ]

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
          - id: pyupgrade
            args: [--py38-plus]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.931
      hooks:
          - id: mypy
            files: ^src/
            args: [--strict]
