# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: DevSkim

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "36 4 * * 3"

permissions:
  contents: read

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443 github.com:443


      - name: Checkout code
        uses: actions/checkout

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif
        with:
          sarif_file: devskim-results.sarif
