name: Lemming

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  lemming:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443 pypi.org:443 files.pythonhosted.org:443


      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
      - name: Set up Python 3.11
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"
      - name: Install Lemming
        run: |
          python -m pip install -U python-lemming
      - name: Run lemming
        run: |
          python -m lemming check . -v
