name: Tests

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@main
        with:
          egress-policy: audit

      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.9
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.10
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.12
      - name: Install nox
        run: python -m pip install nox
      - name: Run nox
        run: nox -s test_coverage
