name: Tests

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@main
        with:
          egress-policy: audit

      - uses: actions/checkout@main
      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with:
          python-version: "3.8"
      - name: Set up Python 3.9
        uses: actions/setup-python@main
        with:
          python-version: "3.9"
      - name: Set up Python 3.10
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Set up Python 3.11
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
      # 3.12 not out yet
      # - name: Set up Python 3.12
      #   uses: actions/setup-python@main
      #   with:
      #     python-version: "3.12"
      - name: Install requirements
        run: python -m pip install python-dotenv nox
      - name: Run nox
        run: nox -s test_coverage
